// Generated by CoffeeScript 1.8.0
(function() {
  var sf;

  sf = require("./ext/ext")(false);

  module.exports = (function(window, sf) {
    window["$sf"] = sf;
    return sf;
  })(window, sf);

}).call(this);
