// Generated by CoffeeScript 1.7.1
(function() {
  var sf;

  sf = require("./host/host")(false);

  (function(window, sf) {
    return window["$sf"] = sf;
  })(window, sf);

  module.exports = sf;

}).call(this);
