// Generated by CoffeeScript 1.8.0
(function() {
  var sf;

  sf = require("./host/host")(false);

  (function(window, sf) {
    if (!window["$sf"]) {
      window["$sf"] = sf;
    }
    return window["_$sf_adjs"] = sf;
  })(window, sf);

  module.exports = sf;

}).call(this);
