// Generated by CoffeeScript 1.7.1
(function() {
  define(["./lang", "./env", "./dom", "./logger"], function(lang, env, dom, logger) {
    return {
      ver: "1-1-0",
      specVersion: "1.1",
      lib: {
        lang: lang,
        dom: dom,
        logger: logger
      },
      env: env,
      host: {},
      ext: {},
      info: {
        errs: [],
        list: []
      }
    };
  });

}).call(this);
